### ISSUE TITLE
No module named 'subtrie'

### ISSUE THREAD

**Issue by icaropires** [emitter-io/python#14]
## Problem

I installed the package version 2.0.0 and get this error when trying using:

![image](https://user-images.githubusercontent.com/18473249/59072147-dbc3eb00-8897-11e9-8452-a2094852cb5d.png)

In version 1.3.0 I can import it or using the source code. The problem is with the package at version 2.0.0

## Details

Package version: 2.0.0
SO: Manjaro, Linux
Python version: 3.7.3

**Comment by Florimond** [comment]
Indeed, the issue is already fixed in the sources, the pip package will be updated tonight.

**Comment by Florimond** [comment]
@icaropires It should work now.

**Comment by icaropires** [comment]
Cool! Now it's working @Florimond. Thank you!
