### ISSUE TITLE
Retrieve key generated

### ISSUE THREAD

**Issue by dvcorreia** [emitter-io/python#15]
I know that's on the documentation as a ToDo, but how can we retrieve the generated key ? Bellow is a sample code, how can we retrieve it following this example?

```python
from emitter import Client

key = "8houiFt2MZ469D0oiBlaibkVcERscGyP"

def onConnect():
    print("Connected!")
    
def onKeygen():
    print("Key generated!")


if __name__ == '__main__':
    emitter = Client()

    emitter.on_connect = onConnect()
    emitter.on_keygen = onKeygen()

    emitter.connect("localhost", 8080, False, 30)
    emitter.keygen(key, "/test/", "rwsl")

    emitter.loop_start()

    while True:
        pass
```

**Comment by Florimond** [comment]
You can add a parameter to your keygen function, and this parameter will contain an object with three fields: `status`, `key`, and `channel`.

Unrelated note, in case you want to test the presence feature, you should be fine using the default `on_presence` handler. But there is a bug with the `optional_handler` that I need to fix.

**Comment by dvcorreia** [comment]
There is any way of waiting for the `on_keygen` callback to end? I am trying to generate a key and then subscribe to a channel for which that key was generated. I've tried polling, threads and I couldn't get it to work.

**Comment by bronte2k7** [comment]
Was a solution found?

**Comment by dvcorreia** [comment]
I don't remember if I managed to find a solution. I ended up switching to the mosquitto broker.
