### ISSUE TITLE
Question about wildcard '#'

### ISSUE THREAD

**Issue by snowflakes918** [emitter-io/python#18]
Hi,

There is one thing that confused me about the source code when I was reading emitter.py and here is the code:

```
def _format_channel(key, channel, options={}):
        k = key.strip("/")
        c = channel.strip("/")
        o = Client._format_options(options)
        
        formatted = "{key}/{channel}/{options}".format(key=k, channel=c, options=o)
        return formatted
```

The code here indicates that whatever the channel is, a "/{options}" will be added after it. However, this makes it impossible to use the wildcard '#' since it has to be the last charactor in the topic.

Or is there a special way to use the wildcard '#' in Emitter?

**Comment by birkanozer** [comment]
I have the same question.
MQTT specifications dictate that the "#" wildcard can only be used at the end of the channel as "/this/is/channels/#". But this library converts this to "\<key\>/this/is/channels/#/\<options\>" which is an unacceptable usage. Is there anything that I missed?

Edit: converted channel name fixed

**Comment by birkanozer** [comment]
@Florimond any update about this problem?

**Comment by Florimond** [comment]
@birkanozer 

From what I understand, you are trying to publish to a channel containing the `#`, which as far as I remember is not supported.

You can:

- publish to a specific channel that doesn't contain any wildcard
- subscribe to a channel pattern possibly containing one or several `+` wildcards
- generate a key for a channel pattern possibly containing one or several `+` and a final `#` wildcard

Do you have a specific use case that would require subscribing to all subchannels whatever their length?

EDIT: I'll check with the main engineer of the project whether it was always the intended behavior. In the meantime, don't hesitate to describe which usecase would be impossible without this feature.

**Comment by birkanozer** [comment]
Hi,
There is probably no use case that one must use `#` instead of multiple `+`. The main benefit would be the simplify the implementation of the subscription functions. At first glance, the documentation of the main projects implies that one can use a `#` wildcard to pub or sub. But after your answer, I've looked again, and `#` was only mentioned in the keygen process. So it's my misunderstanding of the project. Thanks for answering the question.

**Comment by Florimond** [comment]
Yes, the documentation certainly needs some improvement.

Anyway, glad I could help you!
